CREATE SEQUENCE id_seq_crops_quotations AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE crops_quotations (
  id        INTEGER         GENERATED BY DEFAULT AS SEQUENCE id_seq_crops_quotations PRIMARY KEY,
  code      VARCHAR(255)    NOT NULL,
  price     DOUBLE          NOT NULL,
  date      VARCHAR(10)     NOT NULL
);
